#!/usr/bin/env bash

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
#

set -x
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_topmost               off
yabai -m config window_opacity               on
yabai -m config window_border                on
yabai -m config window_shadow                on
yabai -m config window_border_width          4
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config normal_window_border_color   0x00ff17e8
yabai -m config active_window_border_color   0xf0cba6f7
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config layout                       float
yabai -m config top_padding                  6
yabai -m config bottom_padding               6
yabai -m config left_padding                 6
yabai -m config right_padding                6
yabai -m config window_gap                   6
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config window_opacity_duration      0.0
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_animation_duration    0
yabai -m config window_animation_frame_rate  60
yabai -m config window_border_radius         8
yabai -m config window_border_blur           on
yabai -m config window_border_hidpi          on
yabai -m config split_type                   auto
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# Rules
ignored_apps=(
  "1Password"
  "Alfred Preferences"
  "App Store"
  "Bluetooth Explorer"
  "Camera Hub"
  "Dash"
  "Finder"
  "Handbrake"
  "Home"
  "iStat Menus"
  "Logi Options"
  "Logitech Options"
  "Mastonaut"
  "Microsoft Teams"
  "Music"
  "OpenVPN Connect"
  "Photo Booth"
  "Preview"
  "QuickTime Player"
  "Reminders"
  "Skype"
  "Soulver 3"
  "System Information"
  "System Settings"
  "The Unarchiver"
  "Transmit"
  "Twitter"
  "VLC"
  "Zoom"
)

for app in "${ignored_apps[@]}"; do
  yabai -m rule --add app="^${app}$" manage=off mouse_follows_focus=off
done

# make JetBrains products popup windows float
jb='^(IntelliJ IDEA|WebStorm|GoLand|PyCharm|CLion|Rider)$'
yabai -m rule --add app="JetBrains Toolbox" manage=off
yabai -m rule --add app="${jb}" manage=off
yabai -m rule --add app="${jb}" title="^$" manage=on

yabai -m rule --add app="Finder" title=" Info" manage=off
yabai -m rule --add app="Finder" title="Copy" manage=off
yabai -m rule --add app="Finder" title="Mov" manage=off
yabai -m rule --add app="Finder" title="Trash" manage=off
yabai -m rule --add title="Preferences" manage=off
yabai -m rule --add app="iTunes" title="MiniPlayer" manage=off
yabai -m rule --add app="Music" title="MiniPlayer" manage=off
yabai -m rule --add app="Firefox" title="Picture-in-Picture" manage=off
yabai -m rule --add app="Google Chrome" title="Picture in Picture" manage=off
yabai -m rule --add app="Transmit" title="Activity" manage=off

# delete monocle mode lock files from previous sessions
find "${TMPDIR}" -type f -perm +111 -name "yabai_${USER}_monocle_mode_*" -delete

set +x
echo "yabai configuration loaded.."
