set -g status "on"
set -g message-command-style "fg=#232136,bg=#f6c177"
set -g message-style "fg=#908caa,bg=#232136"
set -g pane-active-border-style "fg=#f6c177"
set -g pane-border-style "fg=#56526e"

set -g status-left "#[fg=#232136,bg=#9ccfd8] #S "
set -g status-left-length "100"
set -g status-left-style "none"

set -g status-right "#[none,fg=#908caa] %H:%M "
set -g status-right-length "100"
set -g status-right-style "none"

set -g status-justify "centre"
set -g status-style "none"
setw -g window-status-activity-style "none"
setw -g window-status-current-format "#[fg=#232136,bg=#c4a7e7] #W "
setw -g window-status-format "#[fg=#9ccfd8] #I:#W "
setw -g window-status-separator ""
setw -g window-status-style "none,fg=#9ccfd8"
