set -g status "on"
set -g message-command-style "fg=#cdd6f4,bg=#313244"
set -g message-style "fg=#cdd6f4,bg=#313244"
set -g pane-active-border-style "fg=#89b4fa"
set -g pane-border-style "fg=#45475a"

set -g status-left "#[fg=#1e1e2e,bg=#89b4fa] #S "
set -g status-left-length "100"
set -g status-left-style "none"

set -g status-right "#[none,fg=#a6adc8] %H:%M "
set -g status-right-length "100"
set -g status-right-style "none"

set -g status-justify "centre"
set -g status-style "none"
setw -g window-status-activity-style "none"
setw -g window-status-current-format "#[fg=#1e1e2e,bg=#f5c2e7] #W "
setw -g window-status-format "#[fg=#89b4fa] #I:#W "
setw -g window-status-separator ""
setw -g window-status-style "none,fg=#89b4fa"
