set -g status "on"
set -g message-command-style "fg=#190a0f,bg=#e5b76f"
set -g message-style "fg=#808898,bg=#190a0f"
set -g pane-active-border-style "fg=#f470df"
set -g pane-border-style "fg=#695960"

set -g status-left "#[fg=#190a0f,bg=#8fa5f6] #S "
set -g status-left-length "100"
set -g status-left-style "none"

set -g status-right "#[none,fg=#808898] %H:%M "
set -g status-right-length "100"
set -g status-right-style "none"

set -g status-justify "centre"
set -g status-style "none"
setw -g window-status-activity-style "none"
setw -g window-status-current-format "#[fg=#190a0f,bg=#ef80bf] #W "
setw -g window-status-format "#[fg=#8fbaef] #I:#W "
setw -g window-status-separator ""
setw -g window-status-style "none,fg=#8fbaef"
