## name: Ef Cherie
## upstream: https://github.com/oonamo/ef-themes.nvim/blob/main/extras/kitty/ef-cherie.conf

foreground              #d3cfcf
background              #190a0f
selection_foreground    #d3cfcf
selection_background    #232f3f
url_color               #df7fff
cursor                  #ff5aaf
cursor_text_color       #190a0f

active_border_color     #695960
inactive_border_color   #291f26
bell_border_color       #ff656f
visual_bell_color       none

active_tab_foreground   #190a0f
active_tab_background   #bf9cdf
inactive_tab_foreground #bf9cdf
inactive_tab_background #392a2f
tab_bar_background      #190a0f

mark1_foreground #190a0f
mark1_background #e5b76f
mark2_foreground #190a0f
mark2_background #ef80bf
mark3_foreground #190a0f
mark3_background #8fbaef

color0  #190a0f
color8  #594a4f
color1  #ff7359
color9  #ff656f
color2  #60b444
color10 #60bf88
color3  #e5b76f
color11 #ea9955
color4  #8fa5f6
color12 #a897ef
color5  #ef80bf
color13 #df7fff
color6  #8fbaef
color14 #8fcfdf
color7  #d3cfcf
color15 #ffffff
