## name: Gruvbox Dark Hard
## upstream: https://github.com/morhetz/gruvbox

foreground              #ebdbb2
background              #1d2021
selection_foreground    #fbf1c7
selection_background    #504945
url_color               #83a598
cursor                  #fabd2f
cursor_text_color       #1d2021

active_border_color     #fabd2f
inactive_border_color   #504945
bell_border_color       #fb4934
visual_bell_color       none

active_tab_foreground   #1d2021
active_tab_background   #d3869b
inactive_tab_foreground #a89984
inactive_tab_background #3c3836
tab_bar_background      #1d2021

mark1_foreground #1d2021
mark1_background #fabd2f
mark2_foreground #1d2021
mark2_background #d3869b
mark3_foreground #1d2021
mark3_background #8ec07c

color0  #282828
color8  #928374
color1  #cc241d
color9  #fb4934
color2  #98971a
color10 #b8bb26
color3  #d79921
color11 #fabd2f
color4  #458588
color12 #83a598
color5  #b16286
color13 #d3869b
color6  #689d6a
color14 #8ec07c
color7  #a89984
color15 #ebdbb2
