## name: Rosé Pine Moon
## upstream: https://github.com/rose-pine/kitty/blob/main/dist/rose-pine-moon.conf

foreground              #e0def4
background              #232136
selection_foreground    #e0def4
selection_background    #44415a
url_color               #c4a7e7
cursor                  #56526e
cursor_text_color       #e0def4

active_border_color     #3e8fb0
inactive_border_color   #44415a
bell_border_color       #eb6f92
visual_bell_color       none

active_tab_foreground   #e0def4
active_tab_background   #393552
inactive_tab_foreground #6e6a86
inactive_tab_background #232136
tab_bar_background      #232136

mark1_foreground #232136
mark1_background #f6c177
mark2_foreground #232136
mark2_background #c4a7e7
mark3_foreground #232136
mark3_background #9ccfd8

color0  #393552
color8  #6e6a86
color1  #eb6f92
color9  #eb6f92
color2  #3e8fb0
color10 #3e8fb0
color3  #f6c177
color11 #f6c177
color4  #9ccfd8
color12 #9ccfd8
color5  #c4a7e7
color13 #c4a7e7
color6  #ea9a97
color14 #ea9a97
color7  #e0def4
color15 #e0def4
