# vim:fileencoding=utf-8:foldmethod=marker

[mgr]
cwd = { fg = "#8ec07c" }
find_keyword = { fg = "#fabd2f", bold = true, italic = true, underline = true }
find_position = { fg = "#d3869b", bg = "reset", bold = true, italic = true }
marker_copied = { fg = "#b8bb26", bg = "#b8bb26" }
marker_cut = { fg = "#fb4934", bg = "#fb4934" }
marker_marked = { fg = "#8ec07c", bg = "#8ec07c" }
marker_selected = { fg = "#fabd2f", bg = "#fabd2f" }
count_copied = { fg = "#1d2021", bg = "#b8bb26" }
count_cut = { fg = "#1d2021", bg = "#fb4934" }
count_selected = { fg = "#1d2021", bg = "#fabd2f" }
border_symbol = "│"
border_style = { fg = "#928374" }

[tabs]
active = { fg = "#1d2021", bg = "#83a598", bold = true }
inactive = { fg = "#83a598", bg = "#3c3836" }

[mode]
normal_main = { fg = "#1d2021", bg = "#83a598", bold = true }
normal_alt = { fg = "#83a598", bg = "#3c3836" }
select_main = { fg = "#1d2021", bg = "#8ec07c", bold = true }
select_alt = { fg = "#8ec07c", bg = "#3c3836" }
unset_main = { fg = "#1d2021", bg = "#d5c4a1", bold = true }
unset_alt = { fg = "#d5c4a1", bg = "#3c3836" }

[status]
perm_sep = { fg = "#928374" }
perm_type = { fg = "#83a598" }
perm_read = { fg = "#fabd2f" }
perm_write = { fg = "#fb4934" }
perm_exec = { fg = "#b8bb26" }
progress_label = { fg = "#fbf1c7", bold = true }
progress_normal = { fg = "#b8bb26", bg = "#504945" }
progress_error = { fg = "#fabd2f", bg = "#fb4934" }

[pick]
border = { fg = "#83a598" }
active = { fg = "#d3869b", bold = true }
inactive = {}

[input]
border = { fg = "#83a598" }
title = {}
value = {}
selected = { reversed = true }

[cmp]
border = { fg = "#83a598" }

[tasks]
border = { fg = "#83a598" }
title = {}
hovered = { fg = "#d3869b", bold = true }

[which]
mask = { bg = "#3c3836" }
cand = { fg = "#8ec07c" }
rest = { fg = "#928374" }
desc = { fg = "#d3869b" }
separator = "  "
separator_style = { fg = "#504945" }

[help]
on = { fg = "#8ec07c" }
run = { fg = "#d3869b" }
hovered = { reversed = true, bold = true }
footer = { fg = "#3c3836", bg = "#ebdbb2" }

[spot]
border = { fg = "#83a598" }
title = { fg = "#83a598" }
tbl_col = { fg = "#8ec07c" }
tbl_cell = { fg = "#d3869b", bg = "#504945" }

[notify]
title_info = { fg = "#b8bb26" }
title_warn = { fg = "#fabd2f" }
title_error = { fg = "#fb4934" }

[filetype]
rules = [
	{ mime = "image/*", fg = "#8ec07c" },
	{ mime = "{audio,video}/*", fg = "#fabd2f" },
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#d3869b" },
	{ mime = "application/{pdf,doc,rtf}", fg = "#b8bb26" },
	{ mime = "vfs/{absent,stale}", fg = "#928374" },
	{ url = "*", fg = "#ebdbb2" },
	{ url = "*/", fg = "#83a598" },
]

[icon]
dirs = [
	{ name = ".config", text = "", fg = "#d3869b" },
	{ name = ".git", text = "", fg = "#8ec07c" },
	{ name = ".github", text = "", fg = "#83a598" },
	{ name = ".npm", text = "", fg = "#83a598" },
	{ name = "Desktop", text = "", fg = "#8ec07c" },
	{ name = "Development", text = "", fg = "#8ec07c" },
	{ name = "Documents", text = "", fg = "#8ec07c" },
	{ name = "Downloads", text = "", fg = "#8ec07c" },
	{ name = "Library", text = "", fg = "#8ec07c" },
	{ name = "Movies", text = "", fg = "#8ec07c" },
	{ name = "Music", text = "", fg = "#8ec07c" },
	{ name = "Pictures", text = "", fg = "#8ec07c" },
	{ name = "Public", text = "", fg = "#8ec07c" },
	{ name = "Videos", text = "", fg = "#8ec07c" },
]
conds = [
	{ if = "orphan", text = "", fg = "#ebdbb2" },
	{ if = "link", text = "", fg = "#928374" },
	{ if = "block", text = "", fg = "#d5c4a1" },
	{ if = "char", text = "", fg = "#d5c4a1" },
	{ if = "fifo", text = "", fg = "#d5c4a1" },
	{ if = "sock", text = "", fg = "#d5c4a1" },
	{ if = "sticky", text = "", fg = "#d5c4a1" },
	{ if = "dummy", text = "", fg = "#fb4934" },
	{ if = "dir & hovered", text = "", fg = "#83a598" },
	{ if = "dir", text = "", fg = "#83a598" },
	{ if = "exec", text = "", fg = "#b8bb26" },
	{ if = "!dir", text = "", fg = "#ebdbb2" },
]
