gui:
  sidePanelWidth: 0.3333
  nerdFontsVersion: "3"
  showFileTree: false

  theme:
    activeBorderColor:
      - "#3e8fb0"
      - bold
    inactiveBorderColor:
      - "#6e6a86"
    optionsTextColor:
      - "#9ccfd8"
    selectedLineBgColor:
      - "#3e8fb0"
    inactiveViewSelectedLineBgColor:
      - "#393552"
      - bold
    cherryPickedCommitBgColor:
      - "#ea9a97"
    cherryPickedCommitFgColor:
      - "#2a273f"
    markedBaseCommitFgColor:
      - "#9ccfd8"
    markedBaseCommitBgColor:
      - "#f6c177"
    unstagedChangesColor:
      - "#eb6f92"
    defaultFgColor:
      - "#e0def4"
    searchingActiveBorderColor:
      - "#ea9a97"
      - bold

  branchColors:
    "feature": "#9ccfd8"
    "feat": "#9ccfd8"
    "master": "#c4a7e7"
    "main": "#c4a7e7"

  authorColors:
    "Cyber Oliveira": "#c4a7e7"
    "Monique Oliveira": "#c4a7e7"
    "*": "#9ccfd8"

git:
  parseEmoji: true
  ignoreWhitespaceInDiffView: true
  pagers:
    - pager: delta --dark --paging=never --features=rose-pine-moon
    - pager: delta --dark --paging=never

confirmOnQuit: false
promptToReturnFromSubprocess: false
