gui:
  sidePanelWidth: 0.3333
  nerdFontsVersion: "3"
  showFileTree: false

  theme:
    activeBorderColor:
      - "#fabd2f"
      - bold
    inactiveBorderColor:
      - "#928374"
    optionsTextColor:
      - "#83a598"
    selectedLineBgColor:
      - "#3c3836"
    cherryPickedCommitBgColor:
      - "#504945"
    cherryPickedCommitFgColor:
      - "#fabd2f"
    unstagedChangesColor:
      - "#fb4934"
    defaultFgColor:
      - "#ebdbb2"
    searchingActiveBorderColor:
      - "#fabd2f"

  branchColors:
    "feature": "#83a598"
    "feat": "#83a598"
    "master": "#d3869b"
    "main": "#d3869b"

  authorColors:
    "Cyber Oliveira": "#d3869b"
    "Monique Oliveira": "#d3869b"
    "*": "#83a598"

git:
  parseEmoji: true
  ignoreWhitespaceInDiffView: true
  pagers:
    - pager: delta --dark --paging=never --color-only
    - pager: ydiff -p cat -s --wrap --width={{columnWidth}}
      colorArg: never
    - externalDiffCommand: difft --color=always

confirmOnQuit: false
promptToReturnFromSubprocess: false
