gui:
  sidePanelWidth: 0.3333
  nerdFontsVersion: "3"
  showFileTree: false
  theme:
    activeBorderColor:
      - "#f59280"
      - bold
    inactiveBorderColor:
      - "#695960"
    optionsTextColor:
      - "#bf9cdf"
    selectedLineBgColor:
      - "#232f3f"
    inactiveViewSelectedLineBgColor:
      - "#401f33"
      - bold
    cherryPickedCommitBgColor:
      - "#ef80bf"
    cherryPickedCommitFgColor:
      - "#8fa5f6"
    markedBaseCommitFgColor:
      - "#8fa5f6"
    markedBaseCommitBgColor:
      - "#e5b76f"
    unstagedChangesColor:
      - "#ff7359"
    defaultFgColor:
      - "#d3cfcf"
    searchingActiveBorderColor:
      - "#3a3004"
      - bold
  branchColors:
    "feature": "#8fbaef"
    "feat": "#8fbaef"
    "master": "#ef80bf"
    "main": "#ef80bf"
  authorColors:
    "Cyber Oliveira": "#ef80bf"
    "Monique Oliveira": "#ef80bf"
    "*": "#8fbaef"
git:
  parseEmoji: true
  ignoreWhitespaceInDiffView: true
  diffRenderers:
    - command: delta --dark --paging=never --features=ef-cherie
    - command: delta --dark --paging=never
confirmOnQuit: false
promptToReturnFromSubprocess: false
