require("nvim-treesitter.configs").setup({
	ensure_installed = {
		"bash",
		"c",
		"c_sharp",
		"cmake",
		"comment",
		"commonlisp",
		"cpp",
		"css",
		"diff",
		"dockerfile",
		"eex",
		"elixir",
		"elm",
		"erlang",
		"gitcommit",
		"git_config",
		"git_rebase",
		"gitattributes",
		"gitcommit",
		"gitignore",
		"go",
		"gomod",
		"gosum",
		"gowork",
		"haskell",
		"heex",
		"help",
		"html",
		"javascript",
		"jq",
		"json",
		"json5",
		"lua",
		"make",
		"markdown",
		"perl",
		"php",
		"python",
		"regex",
		"ruby",
		"rust",
		"sql",
		"toml",
		"vim",
		"yaml",
	},
	highlight = { enable = true },
	indent = { enable = true },
	textobjects = { enable = true },
	incremental_selection = {
		enable = true,
		keymaps = {
			init_selection = "gnn", -- set to `false` to disable one of the mappings
			node_incremental = "grn",
			scope_incremental = "grc",
			node_decremental = "grm",
		},
	},
	matchup = {
		enable = true, -- mandatory, false will disable the whole extension
	},
})

vim.o.foldmethod = "expr"
vim.o.foldexpr = "nvim_treesitter#foldexpr()"
