;;; early-init.el --- Early initialization -*- lexical-binding: t; -*-

(defvar evil-want-integration)
(defvar evil-want-keybinding)
(defvar native-comp-async-on-battery-power)
(defvar package-directory-list nil)
(defvar package-gnupghome-dir nil)
(defvar package-quickstart-file nil)
(defvar package-user-dir nil)
(defvar treesit-extra-load-path nil)

(defconst my-cache-directory
  (file-name-as-directory
   (expand-file-name "emacs/"
                     (or (getenv "XDG_CACHE_HOME") "~/.cache/")))
  "Directory for disposable caches generated by Emacs.")

(defconst my-data-directory
  (file-name-as-directory
   (expand-file-name "emacs/"
                     (or (getenv "XDG_DATA_HOME") "~/.local/share/")))
  "Directory for packages and other generated Emacs data.")

(defconst my-state-directory
  (file-name-as-directory
   (expand-file-name "emacs/"
                     (or (getenv "XDG_STATE_HOME") "~/.local/state/")))
  "Directory for persistent state generated by this configuration.")

(dolist (directory (list my-cache-directory my-data-directory
                         my-state-directory))
  (make-directory directory t))

(let ((legacy-package-directory
       (expand-file-name "elpa/" user-emacs-directory)))
  (when (file-directory-p legacy-package-directory)
    (add-to-list 'package-directory-list legacy-package-directory)))

(setq package-user-dir (expand-file-name "elpa/" my-data-directory)
      package-gnupghome-dir
      (expand-file-name "elpa/gnupg/" my-data-directory)
      package-quickstart-file
      (expand-file-name "package-quickstart.el" my-cache-directory)
      treesit-extra-load-path
      (cons (expand-file-name "tree-sitter/" my-data-directory)
            treesit-extra-load-path))

(startup-redirect-eln-cache
 (expand-file-name "eln-cache/" my-cache-directory))

(setq package-enable-at-startup nil
      inhibit-startup-screen t
      frame-inhibit-implied-resize t
      load-prefer-newer t
      native-comp-async-on-battery-power nil
      evil-want-integration t
      evil-want-keybinding nil)

(setq default-frame-alist
      (append '((tool-bar-lines . 0)
                (menu-bar-lines . 0)
                (vertical-scroll-bars . nil)
                (internal-border-width . 12)
                (background-color . "#190a0f")
                (foreground-color . "#d3cfcf")
                (font . "MonoLisaCode 15"))
              default-frame-alist))

;;; early-init.el ends here
