[mgr]
sort_by = "extension"
sort_dir_first = true
linemode = "size_and_mtime"
show_symlink = true
ratio = [0, 2, 3]

[preview]
max_width = 1080
max_height = 1920

[plugin]
prepend_fetchers = [
  { url = "*", run = "git", group = "git" },
  { url = "*/", run = "git", group = "git" },
]

prepend_preloaders = [
  { mime = "{audio,video}/*", run = "mediainfo" },
  { url = "*.csv", run = "duckdb" },
  { url = "*.tsv", run = "duckdb" },
  { url = "*.parquet", run = "duckdb" },
  { url = "*.xlsx", run = "duckdb" },
]

prepend_previewers = [
  { url = "*/", run = "eza-preview" },
  { mime = "{audio,video}/*", run = "mediainfo" },
  { url = "*.csv", run = "duckdb" },
  { url = "*.tsv", run = "duckdb" },
  { url = "*.parquet", run = "duckdb" },
  { url = "*.xlsx", run = "duckdb" },
  { url = "*.db", run = "duckdb" },
  { url = "*.duckdb", run = "duckdb" },
  { url = "*.md", run = "rich-preview" },
  { url = "*.markdown", run = "rich-preview" },
  { url = "*.rst", run = "rich-preview" },
  { url = "*.ipynb", run = "rich-preview" },
  { url = "*.json", run = "rich-preview" },
]
