# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

right_format = "$cmd_duration"

# Inserts a blank line between shell prompts
add_newline = true

[os]
disabled = false

[aws]
disabled = true

[gcloud]
disabled = true

[battery]
disabled = true


# # https://starship.rs/config/#git-branch
# [git_branch]
# symbol = "🔀 "
# format = "| [$symbol$branch]($style) "
#
# # https://starship.rs/config/#character
# [character]
# success_symbol = '[\$](bold black)'
# error_symbol = '[\$](bold black)'

# https://starship.rs/config/#directory
[directory]
style = 'white'
truncate_to_repo = false
truncation_length = 0
