# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

right_format = "$cmd_duration$time"

# Inserts a blank line between shell prompts
add_newline = true
palette = "rose_pine_moon"

[os]
disabled = false

[aws]
disabled = true

[cmd_duration]
show_milliseconds = true

[directory]
style = 'white'
truncate_to_repo = false
truncation_length = 0

[hostname]
ssh_only = false
aliases = { "Studiorama" = "🎙️", "armrama" = "💻" }

[memory_usage]
disabled = false
threshold = 50
# symbol = ' '
style = 'dimmed green'

[status]
disabled = false

[time]
disabled = false


[palettes.rose_pine_moon]
black = "#393552"
red = "#eb6f92"
green = "#3e8fb0"
yellow = "#f6c177"
blue = "#9ccfd8"
purple = "#c4a7e7"
cyan = "#ea9a97"
white = "#d0d0d0"
bright-black = "#6e6a86"
bright-red = "#eb6f92"
bright-green = "#3e8fb0"
bright-yellow = "#f6c177"
bright-blue = "#9ccfd8"
bright-purple = "#c4a7e7"
bright-cyan = "#ea9a97"
bright-white = "#d0d0d0"
base = "#232136"
surface0 = "#2a273f"
surface1 = "#393552"
surface2 = "#44415a"
text = "#d0d0d0"
muted = "#908caa"
