# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

right_format = "$cmd_duration$time"

# Inserts a blank line between shell prompts
add_newline = true
palette = "ef_cherie"

[os]
disabled = false

[aws]
disabled = true

[cmd_duration]
show_milliseconds = true

[directory]
style = 'white'
truncate_to_repo = false
truncation_length = 0

[hostname]
ssh_only = false
aliases = { "Studiorama" = "🎙️", "armrama" = "💻" }

[memory_usage]
disabled = false
threshold = 50
# symbol = ' '
style = 'dimmed green'

[status]
disabled = false

[time]
disabled = false


[palettes.ef_cherie]
black = "#190a0f"
red = "#ff7359"
green = "#60b444"
yellow = "#e5b76f"
blue = "#8fa5f6"
purple = "#ef80bf"
cyan = "#8fbaef"
white = "#d0d0d0"
bright-black = "#808898"
bright-red = "#ff656f"
bright-green = "#60bf88"
bright-yellow = "#ea9955"
bright-blue = "#a897ef"
bright-purple = "#df7fff"
bright-cyan = "#8fcfdf"
bright-white = "#d0d0d0"
base = "#190a0f"
surface0 = "#291f26"
surface1 = "#392a2f"
surface2 = "#594a4f"
text = "#d0d0d0"
muted = "#808898"
