vim.o.foldmethod = "expr"
vim.o.foldexpr = "nvim_treesitter#foldexpr()"

return {
	{
		"nvim-treesitter/nvim-treesitter",
		main = "nvim-treesitter.configs",
		opts = {
			ensure_installed = {
				"awk",
				"bash",
				"c",
				"cmake",
				"comment",
				"cpp",
				"css",
				"csv",
				"diff",
				"dockerfile",
				"eex",
				"elixir",
				"elm",
				"embedded_template",
				"erlang",
				"git_config",
				"git_rebase",
				"gitattributes",
				"gitcommit",
				"gitignore",
				"go",
				"gomod",
				"gosum",
				"gowork",
				"gpg",
				"haskell",
				"haskell_persistent",
				"heex",
				"hlsl",
				"html",
				"http",
				"ini",
				"javascript",
				"jq",
				"json",
				"json5",
				"jsonnet",
				"latex",
				"lua",
				"luadoc",
				"luau",
				"make",
				"markdown",
				"markdown_inline",
				"mermaid",
				"passwd",
				"pem",
				"php",
				"phpdoc",
				"proto",
				"python",
				"requirements",
				"ruby",
				"rust",
				"scss",
				"sql",
				"ssh_config",
				"toml",
				"typescript",
				"vim",
				"vimdoc",
				"xml",
				"yaml",
			},
			endwise = { enable = true },
			highlight = { enable = true, additional_vim_regex_highlighting = false },
			indent = { enable = true, disable = { "python", "ruby" } },
			textobjects = { enable = true },
			incremental_selection = {
				enable = true,
				keymaps = {
					init_selection = "<M-UP>", -- set to `false` to disable one of the mappings
					node_incremental = "<M-UP>",
					scope_incremental = "<M-RIGHT>",
					node_decremental = "<M-DOWN>",
				},
			},
			matchup = { enable = true }, -- mandatory, false will disable the whole extension ,
		},
		build = ":TSUpdate",
	},
}
