require("restore_cursor")

require("plugins.lualine")
require("plugins.notify")
require("plugins.toggleterm")
require("plugins.refactoring")
require("plugins.tree")
require("plugins.mason")
require("plugins.treesitter")
require("plugins.treesitter-refactor")
require("plugins.treesitter-textobjects")
require("plugins.treesitter-rainbow")
require("plugins.treesitter-context")
require("plugins.cmp")
require("plugins.haskell-tools")
require("plugins.telescope")
