[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
python.uv_venv_auto = true
disable_backends = ["asdf"]

[tools]
neovim = { version = "latest", os = ["linux", "macos"] }
starship = { version = "latest", os = ["linux", "macos"] }
opencode = { version = "latest", os = ["linux"] }
bat = { version = "latest", os = ["linux", "macos"] }
"aqua:fish-shell/fish-shell" = { version = "latest", os = ["linux"] }

go = { version = "latest", os = ["linux", "macos"] }
erlang = { version = "latest", os = ["linux", "macos"] }
elixir = { version = "latest", os = ["linux", "macos"] }
node = { version = "latest", os = ["linux", "macos"] }
watchexec = { version = "latest", os = ["linux", "macos"] }
rust = { version = "latest", os = ["linux", "macos"] }
uv = { version = "latest", os = ["linux", "macos"] }
fd = { version = "latest", os = ["linux", "macos"] }
ruby = { version = "latest", os = ["linux", "macos"] }
lua = { version = "latest", os = ["linux", "macos"] }
"aqua:jdx/usage" = { version = "latest", os = ["linux", "macos"] }
delta = { version = "latest", os = ["linux", "macos"] }

"cargo:git-delta" = { version = "latest", os = ["freebsd"] }
"cargo:fd-find" = { version = "latest", os = ["linux", "freebsd"] }

"github:sst/opencode" = { version = "latest", os = ["linux", "macos"] }
"aqua:golangci/golangci-lint" = "latest"
babashka = { version = "latest", exe = "bb" }

leiningen = "2.12"

ghcup = "latest"
lazygit = "latest"
"aqua:spinel-coop/rv" = "latest"
tree-sitter = "latest"
yazi = "latest"
television = "latest"
vivid = "latest"
carapace = "latest"
fzf = "latest"
duckdb = "latest"
eza = "latest"

amazon-ecs-cli = "latest"
ansible = { version = "latest", pipx_args = "--python=/Users/cyber/.local/share/mise/installs/python/3.12.14/bin/python3.12 --include-deps", uvx = "false" }
awscli = "latest"
azure-cli = "latest"
cmake = "latest"
coreutils = "latest"
cowsay = "latest"
dasel = "latest"
deno = "latest"
dotnet = "latest"
elm = "latest"
ffmpeg = "latest"
fastfetch = "latest"
flyctl = "latest"
fx = "latest"
gh = "latest"
git-lfs = "latest"
hugo = "latest"
imagemagick = "latest"
jq = "latest"
lnav = "latest"
luajit = "latest"
make = "latest"
ninja = "latest"
ollama = "latest"
php = "latest"
pipx = "latest"
postgres = "18"
powershell = "latest"
python = ["3.10.21", "3.11.16", "3.12.14", "3.14.7"]
resvg = "latest"
ripgrep = "latest"
sqlite = "latest"
yarn = "4.18.0"
yt-dlp = "latest"
zoxide = "latest"
codex = "latest"
