[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
python.uv_venv_auto = true
disable_backends = ["asdf"]

[tools]
neovim = { version = "latest", os = ["linux"] }
starship = { version = "latest", os = ["linux"] }
opencode = { version = "latest", os = ["linux"] }
bat = { version = "latest", os = ["linux"] }
"aqua:fish-shell/fish-shell" = { version ="latest", os = ["linux"] }

go = { version = "latest", os = ["linux", "macos"] }
erlang = { version = "latest", os = ["linux", "macos"] }
elixir = { version = "latest", os = ["linux", "macos"] }
node = { version = "latest", os = ["linux", "macos"] }
watchexec = { version = "latest", os = ["linux", "macos"] }
rust = { version = "latest", os = ["linux", "macos"] }
uv = { version = "latest", os = ["linux", "macos"] }
fd = { version = "latest", os = ["linux", "macos"] }
ruby = { version = "latest", os = ["linux", "macos"] }
lua = { version = "latest", os = ["linux", "macos"] }
"aqua:jdx/usage" = { version = "latest", os = ["linux", "macos"] }
delta = { version = "latest", os = ["linux", "macos"] }

"cargo:git-delta" = { version = "latest", os = ["freebsd"] }
"cargo:fd-find" = { version = "latest", os = ["linux", "freebsd"] }

"github:sst/opencode" = { version = "latest", os = ["linux", "macos"] }
"aqua:golangci/golangci-lint" = "latest"
babashka = { version = "latest", exe = "bb" }

ghcup = "latest"
lazygit = "latest"
"aqua:spinel-coop/rv" = "latest"
leiningen = "2.12"
