[settings]
disable_tools = [
  "neovim",
  "starship",
  "opencode",
  "bat",
  "aqua:fish-shell/fish-shell",
  "go",
  "erlang",
  "elixir",
  "node",
  "watchexec",
  "rust",
  "uv",
  "fd",
  "ruby",
  "lua",
  "aqua:jdx/usage",
  "delta",
  "github:sst/opencode",
  "ghcup",
  "aqua:spinel-coop/rv",
  "tree-sitter",
  "yazi",
  "television",
  "vivid",
  "carapace",
  "fzf",
  "duckdb",
  "amazon-ecs-cli",
  "ansible",
  "awscli",
  "azure-cli",
  "cmake",
  "coreutils",
  "dasel",
  "deno",
  "dotnet",
  "elm",
  "ffmpeg",
  "fastfetch",
  "flyctl",
  "fx",
  "gh",
  "git-lfs",
  "hugo",
  "imagemagick",
  "jq",
  "lnav",
  "luajit",
  "make",
  "ninja",
  "ollama",
  "php",
  "pipx",
  "postgres",
  "powershell",
  "resvg",
  "ripgrep",
  "sqlite",
  "zoxide",
  "codex",
]
