[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
python.uv_venv_auto = true
disable_backends = ["asdf"]

[tools]
neovim = { version = "latest", os = ["linux", "macos"] }
starship = { version = "latest", os = ["linux", "macos"] }
opencode = { version = "latest", os = ["linux"] }
bat = { version = "latest", os = ["linux", "macos"] }
"aqua:fish-shell/fish-shell" = { version = "latest", os = ["linux"] }

go = { version = "latest", os = ["linux", "macos"] }
erlang = { version = "latest", os = ["linux", "macos"] }
elixir = { version = "latest", os = ["linux", "macos"] }
node = { version = "latest", os = ["linux", "macos"] }
watchexec = { version = "latest", os = ["linux", "macos"] }
rust = { version = "latest", os = ["linux", "macos"] }
uv = { version = "latest", os = ["linux", "macos"] }
fd = { version = "latest", os = ["linux", "macos"] }
ruby = { version = "latest", os = ["linux", "macos"] }
lua = { version = "latest", os = ["linux", "macos"] }
"aqua:jdx/usage" = { version = "latest", os = ["linux", "macos"] }
delta = { version = "latest", os = ["linux", "macos"] }

"cargo:git-delta" = { version = "latest", os = ["freebsd"] }
"cargo:fd-find" = { version = "latest", os = ["linux", "freebsd"] }

"github:sst/opencode" = { version = "latest", os = ["linux", "macos"] }
"aqua:golangci/golangci-lint" = "latest"
babashka = { version = "latest", exe = "bb" }

leiningen = "2.12"
lazygit = "latest"
eza = "latest"
cowsay = "latest"
python = ["3.10.21", "3.11.16", "3.12.14", "3.14.7"]
yarn = "4.18.0"
yt-dlp = "latest"

# Linux + macOS only
ghcup = { version = "latest", os = ["linux", "macos"] }
"aqua:spinel-coop/rv" = { version = "latest", os = ["linux", "macos"] }
tree-sitter = { version = "latest", os = ["linux", "macos"] }
yazi = { version = "latest", os = ["linux", "macos"] }
television = { version = "latest", os = ["linux", "macos"] }
vivid = { version = "latest", os = ["linux", "macos"] }
carapace = { version = "latest", os = ["linux", "macos"] }
fzf = { version = "latest", os = ["linux", "macos"] }
duckdb = { version = "latest", os = ["linux", "macos"] }
amazon-ecs-cli = { version = "latest", os = ["linux", "macos"] }
ansible = { version = "latest", pipx_args = "--python={{ xdg_data_home }}/mise/installs/python/3.12.14/bin/python3.12 --include-deps", uvx = false, os = ["linux", "macos"] }
awscli = { version = "latest", os = ["linux", "macos"] }
azure-cli = { version = "latest", os = ["linux", "macos"] }
cmake = { version = "latest", os = ["linux", "macos"] }
coreutils = { version = "latest", os = ["linux", "macos"] }
dasel = { version = "latest", os = ["linux", "macos"] }
deno = { version = "latest", os = ["linux", "macos"] }
dotnet = { version = "latest", os = ["linux", "macos"] }
elm = { version = "latest", os = ["linux", "macos"] }
ffmpeg = { version = "latest", os = ["linux", "macos"] }
fastfetch = { version = "latest", os = ["linux", "macos"] }
flyctl = { version = "latest", os = ["linux", "macos"] }
fx = { version = "latest", os = ["linux", "macos"] }
gh = { version = "latest", os = ["linux", "macos"] }
git-lfs = { version = "latest", os = ["linux", "macos"] }
hugo = { version = "latest", os = ["linux", "macos"] }
imagemagick = { version = "latest", os = ["linux", "macos"] }
jq = { version = "latest", os = ["linux", "macos"] }
lnav = { version = "latest", os = ["linux", "macos"] }
luajit = { version = "latest", os = ["linux", "macos"] }
make = { version = "latest", os = ["linux", "macos"] }
ninja = { version = "latest", os = ["linux", "macos"] }
ollama = { version = "latest", os = ["linux", "macos"] }
php = { version = "latest", os = ["linux", "macos"] }
pipx = { version = "latest", os = ["linux", "macos"] }
postgres = { version = "18", os = ["linux", "macos"] }
powershell = { version = "latest", os = ["linux", "macos"] }
resvg = { version = "latest", os = ["linux", "macos"] }
ripgrep = { version = "latest", os = ["linux", "macos"] }
sqlite = { version = "latest", os = ["linux", "macos"] }
zoxide = { version = "latest", os = ["linux", "macos"] }
codex = { version = "latest", os = ["linux", "macos"] }
